### ISSUE TITLE
object.d.ts: invalid TypeScript declarations

### ISSUE THREAD

**Issue by thetric** [bpmn-io/min-dash#26]
### Describe the Bug

We can't use version 4.1.0 because it includes invalid TypeScript definitions:

```
Error: node_modules/min-dash/dist/object.d.ts:72:77 - error TS2344: Type 'V' does not satisfy the constraint 'keyof T'.
  Type 'any[]' is not assignable to type 'keyof T'.

72 export function pick<T, V extends any[]>(target: T, properties: V): Pick<T, V>;
                                                                               ~

Error: node_modules/min-dash/dist/object.d.ts:82:77 - error TS2344: Type 'V' does not satisfy the constraint 'string | number | symbol'.
  Type 'any[]' is not assignable to type 'string | number | symbol'.

82 export function omit<T, V extends any[]>(target: T, properties: V): Omit<T, V>;
                                                                               ~
```

This is introduced in https://github.com/bpmn-io/min-dash/pull/25.

### Steps to Reproduce

Can also be reproduced in the TypeScript Playground: https://www.typescriptlang.org/play?ts=5.0.4#code/PQKhCgAIUhhB7ADgT0gFwBYFNIDcCGANgK5YDOk8AZpEYZTZjlgHbEC2WATvgEaE54AdxaREXJNzQBLcpCoT2lFoK6R28LjjLxiXAMaDeAKyz60FNPFpQYafFwDmWNJRNm0AOkgAlF3pZLbHQHZ1d4d3NPW1tIAAFEB3wleycXSAAVYNSwt1NzdGt9JFQraOh4xJ4lHT1DTODagyN81wV4JSEMaX0MQshilDEJRClZMnKQYHAsAA9ETTbiFnNpeFF8MjJpRxYAHgyAGkgAVQA+AAoclwAuTOOmwzuTgEo7jMgAMlOAbnBwUAQCoIIZMPBEUgUai0Qj0aFg1gcbh8ASUETDSRcGRydpKdaqdSabS6Zp5DyWaz4WLXcKRLy+fxcQLobKhdIRVqTWIJJIpNmuLI4GlkgpWAYlQqTSq8yCPLAARgaOCo0i4ZFccpFbUUkC6PT6YsGqHEmOxE25VWSspJhgATErZWZ1gATa11FoeeQ6vW9fpGjGjLHjSbTOYLLHyZarda0LY7fZHU7HABqlxp7weNoVz0z7ttd2Tb0yX1OJeTfwBYFiINKwQIJDk0LoDBZzDYnB4-EE6JNgbNXo6ygJGi0btJHPJ-SpFWFE6iDLQASCQv5Wq5FR51RCaQFrJ3Wr9ErKFplcsVgvkqvVY-qc+1g59BqKEt7Y3IUs3Vrl9ovZCdLFdTU7wHTpul9Q0XxGN9zQ3S0aizABmB1MFVQCswPXFdTAp9xSGV8g3fWxQ3mRZIxWGQY02bZdgOY4ThTY4AHU035DMb2zJN2PzSBk1zZoELuRiiw+b4TjLEtGIrQFqyPOsIUbGhm3hYJEQ7FFu1EfD+0w-FKDUEdiXdLUKRsGdVzvbw-EXJll23XILJiWCZWFC9ZzpQ9QXgD84PYigAHkVD0wlRyAukKEwx8PONKCCLIIiZhIiMqCjCiNjjGiMhYnc2M8XK5TIO58BYZAAG0AF1hKkqsKgAcRcCh8EgFR1SwV0tNQJtIEcaRcFYLVjiEaRMFoUQkFSohIGdLAqHwYhCFcetSHXGBPz5fdXPMxhgnswN8FS7yZUSYaLyOnCwWatBWvBBsDq3KaZrmtBk3kh0tDIR7+i0azRGkLacHayb4DkFh4FcOZpHVZb4i+gIRuQeKw1I5LyLWUQwiuVi4eOU67gudUuGkFhHAAH3bXhuBecrjnu2b5uehsAH5CuKosiuQKqgRgABleraCa8hLramK0A6xSup6vrgLFMEyFGfRftkV1FqwKGsgh9RiHsS7bOAorXRhmzICGqHVrs9INv3ZTtHZXb9pPLdTodR3peCC6ruV26rWVh1vbFP8vEclaDdEBEBE4Fg0ARxKlhRmN-YOLKwjYnHIDxtACaJ0mOHJrhKbK45leZ5BKv+aSKgABR6ABrANoJA1txd6kP+RNnyaXtq0tPGQPocZFgo-DGPo006vaJ4yA5kugCGuK8rE9ue5a9igsi0r-Qq7H1MOdiNea+bYUu-IY45n0EhnUJxwG+6puhxgznpS3dunId4Xu+gblg7NyPoGIweyOHyg7AhqbwnrMKezoZ6lTKvPNAydX7kBXncPyQC0CbzONvYEskcDKyhIpWELYETtmRF2NEml4HhR1LpTQwVDLjjClOak5k6SWT7rZNynIO5rVyBbey7kIKeU9vBd0-lArUIMuxYy9dIr8OiqaN+UwEp-2RgAjszgMbZX6pAXKnh8pF3KqzYqPwgA

(copy&pasta of https://github.com/bpmn-io/min-dash/blob/master/lib/object.d.ts)

### Expected Behavior

This library should provide valid TypeScript declarations.

### Environment

- Host (Browser/Node version), if applicable: Node 18.16.0, TypeScript 4.8.4
- OS: Win 10
- Library version: 4.1.0

**Comment by nikku** [comment]
Thanks for the report. Released fix with `v4.1.1`.

**Comment by thetric** [comment]
Wow, that was fast 🤯
